---
kind: pipeline
type: kubernetes
name: callisto-ingress

platform:
  os: linux
  arch: amd64

steps:
  - name: lint helm files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_files:
        - ./helm/values/dev-values.yaml

  - name: deploy to dev
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values_files:
        - ./helm/values/dev-values.yaml
      release: callisto-ingress-nginx
      kube_certificate: 
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: dev_kube_token
    when:
      event: push
      branch: main


---
kind: pipeline
type: kubernetes
name: callisto-ingress-test-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-ingress

steps:
  - name: lint helm files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_files:
        - ./helm/values/test-values.yaml

  - name: deploy to test
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-test
      mode: upgrade
      chart: ./helm
      values_files:
        - ./helm/values/test-values.yaml
      release: callisto-ingress-nginx
      kube_certificate: 
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: test_kube_token
    when:
      event: push
      branch: main

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - callisto-ingress

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
