---
kind: pipeline
type: kubernetes
name: lint-files

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
      - push
      - pull_request
    exclude:
      - promote

steps:
  - name: lint_helm_files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_files:
        - ./helm/values/dev-values.yaml
        - ./helm/values/test-values.yaml
        - ./helm/values/prod-values.yaml

---
kind: pipeline
type: kubernetes
name: promotion-check

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - promote

steps:
  - name: branch-check
    pull: if-not-exists
    image: alpine:latest
    commands:
      - echo Cannot promote from non 'main' branch
      - exit 1
    when:
      branch:
        exclude:
          - main

  - name: environment-check
    pull: if-not-exists
    image: alpine:latest
    commands:
      - echo Cannot promote to a non prod environment
      - exit 1
    when:
      target:
        exclude:
          - production

  - name: build-check
    pull: if-not-exists
    image: drone/cli:1.6.2-alpine
    environment:
      DRONE_BUILD_PARENT: ${DRONE_BUILD_PARENT}
      DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - chmod +x ./pipeline-scripts/check-build-promotion.sh
      - ./pipeline-scripts/check-build-promotion.sh

---
kind: pipeline
type: kubernetes
name: callisto-ingress-dev-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

trigger:
  event:
    include:
      - push
    exclude:
      - promote
  branch:
    - main

steps:
  - name: deploy to dev
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values_files:
        - ./helm/values/dev-values.yaml
      release: callisto-ingress-nginx
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: dev_kube_token

  - name: check dev up
    pull: if-not-exists
    image: alpine/curl:3.14
    commands:
      - curl -s https://raw.githubusercontent.com/UKHomeOffice/callisto-ui-nginx/main/scripts/is-url-up.sh >up.sh
      - chmod +x ./up.sh
      - ./up.sh https://web.dev.callisto-notprod.homeoffice.gov.uk/health
      - ./up.sh https://timecard.dev.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://accruals.dev.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://person.dev.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
    when:
      event:
        - push
      branch:
        - main
    depends_on:
      - deploy to dev

---
kind: pipeline
type: kubernetes
name: callisto-ingress-test-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-ingress-dev-deploy

trigger:
  event:
    include:
      - push
    exclude:
      - promote
  branch:
    - main

steps:
  - name: deploy to test
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-test
      mode: upgrade
      chart: ./helm
      values_files:
        - ./helm/values/test-values.yaml
      release: callisto-ingress-nginx
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: test_kube_token

  - name: check test up
    pull: if-not-exists
    image: alpine/curl:3.14
    commands:
      - curl -s https://raw.githubusercontent.com/UKHomeOffice/callisto-ui-nginx/main/scripts/is-url-up.sh >up.sh
      - chmod +x ./up.sh
      - ./up.sh https://web.test.callisto-notprod.homeoffice.gov.uk/health
      - ./up.sh https://timecard.test.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://accruals.test.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://person.test.callisto-notprod.homeoffice.gov.uk/swagger-ui/index.html
    depends_on:
      - deploy to test

---
kind: pipeline
type: kubernetes
name: callisto-ingress-prod-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - promotion-check

trigger:
  event:
    - promote
  target:
    exclude:
    - production
#To reinstate prod deployment change the trigger to:
#trigger:
#  event:
#    - promote
#  target:
#      - production

steps:
  - name: deploy to prod
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-prod
      mode: upgrade
      chart: ./helm
      values_files:
        - ./helm/values/prod-values.yaml
      release: callisto-ingress-nginx
      kube_certificate:
        from_secret: prod_kube_api_certificate
      kube_api_server:
        from_secret: prod_kube_api_url
      kube_token:
        from_secret: prod_kube_token

  - name: check prod up
    pull: if-not-exists
    image: alpine/curl:3.14
    commands:
      - curl -s https://raw.githubusercontent.com/UKHomeOffice/callisto-ui-nginx/main/scripts/is-url-up.sh >up.sh
      - chmod +x ./up.sh
      - ./up.sh https://web.callisto.homeoffice.gov.uk/health
      - ./up.sh https://timecard.callisto.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://accruals.callisto.homeoffice.gov.uk/swagger-ui/index.html
      - ./up.sh https://person.callisto.homeoffice.gov.uk/swagger-ui/index.html
    depends_on:
      - deploy to prod

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure

slack: &slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook_url
    channel: callisto-tech-notifications
    username: Drone

depends_on:
  - callisto-ingress-dev-deploy
  - callisto-ingress-test-deploy
  - callisto-ingress-prod-deploy

steps:
  - name: slack
    <<: *slack
    settings:
      template: |
        {{#success build.status}}
          <${DRONE_BUILD_LINK}|Build #{{ build.number }}> succeeded! :tada:
        {{else}}
          <${DRONE_BUILD_LINK}|Build #{{ build.number }}> failed :broken_heart:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
    when:
      event:
        - push

  - name: slack promotion
    <<: *slack
    settings:
      template: >
        {{#success build.status}}
          :rocket: Successful *{{uppercasefirst build.deployTo}}* deployment for *{{repo.name}}* <${DRONE_BUILD_LINK}| build #{{build.number}}>.          
        {{else}}
          :zombie: Problem *{{uppercasefirst build.deployTo}}* deployment failed for *{{repo.name}}* <${DRONE_BUILD_LINK}| build #{{build.number}}>.
        {{/success}}
    when:
      event:
        - promote

---
kind: pipeline
type: kubernetes
name: urgent notifications

trigger:
  status:
    - failure

depends_on:
  - callisto-ingress-dev-deploy
  - callisto-ingress-test-deploy
  - callisto-ingress-prod-deploy

slack: &slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_urgent_webhook_url
    channel: callisto-urgent-tech-notifications
    username: Drone

steps:
  - name: slack_build_urgent
    <<: *slack
    settings:
      template: |
        <${DRONE_BUILD_LINK}|Build #{{build.number}}> failed :this-is-fine-fire:
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Author: {{ build.author }}
    when:
      branch:
        - main

  - name: slack_deploy_urgent
    <<: *slack
    settings:
      template: |
        :alert: Problem *{{uppercasefirst build.deployTo}}* deployment failed for *{{repo.name}}* <${DRONE_BUILD_LINK}| build #{{build.number}}>.
    when:
      event:
        - promote
